program nrings_svg
    !
    ! SVG Torsion Rings Generator
    ! Modified from nrings.f for web-friendly SVG output
    ! 
    ! Input: Tab-separated torsion angles file
    ! Output: SVG visualization with interactive elements
    !
    implicit none
    
    integer :: i, j, n, nc, first, last, nang
    integer :: unit_in, unit_out, ios
    integer :: ntor(10)
    real :: did(5000, 8)
    real :: ix(5000), iy(5000), x(5000), y(5000)
    real :: pi, deg_to_rad, rad_to_deg
    real :: angle_rad, angle_deg, radius, cx, cy
    real :: x1, y1, x2, y2
    real :: scale, offset_x, offset_y
    character(len=3) :: al(10)
    character(len=256) :: input_file, output_file, title
    character(len=256) :: line
    real :: color_r, color_g, color_b
    
    ! Constants
    pi = 4.0 * atan(1.0)
    deg_to_rad = pi / 180.0
    rad_to_deg = 180.0 / pi
    
    ! Initialize
    n = 0
    nc = 7  ! Default to 7 torsions (standard for RNA)
    ntor = 0
    al(1) = 'α  '
    al(2) = 'β  '
    al(3) = 'γ  '
    al(4) = 'δ  '
    al(5) = 'ε  '
    al(6) = 'ζ  '
    al(7) = 'χ  '
    
    ! Get command line arguments
    if (command_argument_count() < 1) then
        write(*, '(A)') 'Usage: ./nrings_svg <input_file> [output_file] [title]'
        write(*, '(A)') '  input_file:  Tab-separated torsion angles'
        write(*, '(A)') '  output_file: SVG output (default: rings.svg)'
        write(*, '(A)') '  title:       Plot title (default: Torsion Rings)'
        stop
    end if
    
    call get_command_argument(1, input_file)
    
    ! Output file
    if (command_argument_count() >= 2) then
        call get_command_argument(2, output_file)
    else
        output_file = 'rings.svg'
    end if
    
    ! Title
    if (command_argument_count() >= 3) then
        call get_command_argument(3, title)
    else
        title = 'Torsion Rings'
    end if
    
    ! Read input file
    unit_in = 10
    open(unit=unit_in, file=trim(input_file), status='old', action='read', iostat=ios)
    if (ios /= 0) then
        write(*, '(A,A)') 'Error opening input file: ', trim(input_file)
        stop
    end if
    
    ! Read torsion angles
    n = 0
    do while (.true.)
        read(unit_in, '(A)', iostat=ios) line
        if (ios /= 0) exit
        
        ! Skip empty lines
        if (len_trim(line) == 0) cycle
        
        n = n + 1
        if (n > 5000) then
            write(*, '(A)') 'Error: Too many residues (max 5000)'
            stop
        end if
        
        ! Parse tab-separated values
        read(line, *, iostat=ios) (did(n, j), j=1, 7)
        if (ios /= 0) then
            write(*, '(A,I0)') 'Warning: Could not parse line ', n
            n = n - 1
        end if
    end do
    close(unit_in)
    
    if (n < 1) then
        write(*, '(A)') 'Error: No valid torsion data found'
        stop
    end if
    
    write(*, '(A,I0)') 'Read ', n, ' residues with torsion angles'
    
    ! Create SVG
    unit_out = 11
    open(unit=unit_out, file=trim(output_file), status='replace', action='write')
    
    ! SVG header
    write(unit_out, '(A)') '<?xml version="1.0" encoding="UTF-8"?>'
    write(unit_out, '(A)') '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" width="1200" height="800">'
    write(unit_out, '(A)') '  <defs>'
    write(unit_out, '(A)') '    <style>'
    write(unit_out, '(A)') '      .title { font-size: 20px; font-weight: bold; text-anchor: middle; }'
    write(unit_out, '(A)') '      .ring-label { font-size: 12px; font-weight: bold; text-anchor: middle; }'
    write(unit_out, '(A)') '      .angle-text { font-size: 10px; text-anchor: middle; fill: #333; }'
    write(unit_out, '(A)') '      .circle-bg { stroke: #ddd; stroke-width: 1; fill: none; }'
    write(unit_out, '(A)') '      .circle-line { stroke-width: 2; fill: none; }'
    write(unit_out, '(A)') '      .grid-line { stroke: #e0e0e0; stroke-width: 0.5; }'
    write(unit_out, '(A)') '      .tick-line { stroke: #666; stroke-width: 1; }'
    write(unit_out, '(A)') '    </style>'
    write(unit_out, '(A)') '  </defs>'
    
    ! Background
    write(unit_out, '(A)') '  <rect width="1200" height="800" fill="#ffffff"/>'
    
    ! Title
    write(unit_out, '(A,A,A)') '  <text class="title" x="600" y="30">', trim(title), '</text>'
    
    ! Draw rings for each torsion type
    radius = 60
    scale = 1.5
    
    ! Calculate positions (7 columns, roughly arranged in 3 rows)
    call draw_rings(unit_out, did, n, nc, radius, scale, al)
    
    ! Footer
    write(unit_out, '(A)') '  <text x="600" y="780" style="font-size: 10px; text-anchor: middle; fill: #999;">'
    write(unit_out, '(A)') '    Generated by Torsion Rings SVG Tool | Angles in degrees'
    write(unit_out, '(A)') '  </text>'
    
    write(unit_out, '(A)') '</svg>'
    close(unit_out)
    
    write(*, '(A,A)') 'SVG output written to: ', trim(output_file)

contains

    subroutine draw_rings(unit_out, did, n, nc, radius, scale, al)
        integer, intent(in) :: unit_out, n, nc
        real, intent(in) :: did(:, :), radius, scale
        character(len=3), intent(in) :: al(:)
        
        integer :: i, j, col, row, angle_steps
        integer :: ring_x, ring_y
        real :: angle_rad, x_point, y_point
        real :: cx, cy, r
        character(len=20) :: color_str
        
        ! Layout: 7 rings in a grid
        col = 0
        row = 0
        
        do j = 1, min(nc, 7)
            col = col + 1
            if (col > 3) then
                col = 1
                row = row + 1
            end if
            
            ring_x = 100 + (col - 1) * 350
            ring_y = 120 + row * 200
            
            ! Draw ring for torsion j
            call draw_single_ring(unit_out, did(:, j), n, ring_x, ring_y, radius, &
                                   al(j), get_color(j, color_str))
        end do
    end subroutine draw_rings
    
    subroutine draw_single_ring(unit_out, angles, n, cx, cy, radius, label, color)
        integer, intent(in) :: unit_out, n, cx, cy
        real, intent(in) :: angles(:), radius
        character(len=3), intent(in) :: label
        character(len=20), intent(in) :: color
        
        integer :: i, points
        real :: angle_deg, angle_rad, x_point, y_point
        real :: pi, deg_to_rad
        character(len=500) :: path_str
        
        pi = 4.0 * atan(1.0)
        deg_to_rad = pi / 180.0
        
        ! Background circles (30, 60, 90 degree rings)
        write(unit_out, '(A,I0,A,I0,A,F0.1,A)') &
            '  <circle class="circle-bg" cx="', cx, '" cy="', cy, '" r="', radius * 0.33, '"/>'
        write(unit_out, '(A,I0,A,I0,A,F0.1,A)') &
            '  <circle class="circle-bg" cx="', cx, '" cy="', cy, '" r="', radius * 0.67, '"/>'
        write(unit_out, '(A,I0,A,I0,A,F0.1,A)') &
            '  <circle class="circle-bg" cx="', cx, '" cy="', cy, '" r="', radius, '"/>'
        
        ! Cross hairs
        write(unit_out, '(A,I0,A,I0,A,I0,A,I0,A,I0,A)') &
            '  <line class="tick-line" x1="', cx - nint(radius * 1.1), '" y1="', cy, &
            '" x2="', cx + nint(radius * 1.1), '" y2="', cy, '"/>'
        write(unit_out, '(A,I0,A,I0,A,I0,A,I0,A)') &
            '  <line class="tick-line" x1="', cx, '" y1="', cy - nint(radius * 1.1), &
            '" x2="', cx, '" y2="', cy + nint(radius * 1.1), '"/>'
        
        ! Draw angle points
        do i = 1, n
            angle_deg = angles(i)
            if (abs(angle_deg - 999.0) < 0.1) cycle  ! Skip missing atoms
            
            angle_rad = angle_deg * deg_to_rad
            x_point = cx + radius * cos(angle_rad)
            y_point = cy - radius * sin(angle_rad)  ! Negate because SVG y increases downward
            
            ! Draw point
            write(unit_out, '(A,F0.1,A,F0.1,A,A,A)') &
                '  <circle cx="', x_point, '" cy="', y_point, '" r="2" fill="', &
                trim(color), '" opacity="0.7"/>'
        end do
        
        ! Draw angle scale labels
        call draw_angle_labels(unit_out, cx, cy, radius)
        
        ! Ring label
        write(unit_out, '(A,I0,A,I0,A,A,A)') &
            '  <text class="ring-label" x="', cx, '" y="', cy - nint(radius * 1.25), &
            '">', trim(label), '</text>'
        
        ! Count residues with valid angles
        points = 0
        do i = 1, n
            if (abs(angles(i) - 999.0) >= 0.1) points = points + 1
        end do
        write(unit_out, '(A,I0,A,I0,A,I0,A)') &
            '  <text class="angle-text" x="', cx, '" y="', &
            cy + nint(radius * 1.2), '">n=', points, '</text>'
        
    end subroutine draw_single_ring
    
    subroutine draw_angle_labels(unit_out, cx, cy, radius)
        integer, intent(in) :: unit_out, cx, cy
        real, intent(in) :: radius
        
        ! Cardinal directions (0, 90, 180, 270 degrees)
        write(unit_out, '(A,I0,A,F0.1,A)') &
            '  <text class="angle-text" x="', cx + nint(radius + 15), '" y="', real(cy) + 4.0, &
            '">0°</text>'
        write(unit_out, '(A,I0,A,F0.1,A)') &
            '  <text class="angle-text" x="', cx, '" y="', real(cy - nint(radius)) - 10.0, &
            '">90°</text>'
        write(unit_out, '(A,I0,A,F0.1,A)') &
            '  <text class="angle-text" x="', cx - nint(radius) - 15, '" y="', real(cy) + 4.0, &
            '">180°</text>'
        write(unit_out, '(A,I0,A,F0.1,A)') &
            '  <text class="angle-text" x="', cx, '" y="', real(cy + nint(radius)) + 15.0, &
            '">270°</text>'
    end subroutine draw_angle_labels
    
    function get_color(index, color_str) result(color)
        integer, intent(in) :: index
        character(len=20), intent(inout) :: color_str
        character(len=20) :: color
        
        select case (index)
        case (1)
            color = '#FF6B6B'  ! Red
        case (2)
            color = '#4ECDC4'  ! Teal
        case (3)
            color = '#45B7D1'  ! Blue
        case (4)
            color = '#FFA502'  ! Orange
        case (5)
            color = '#95E1D3'  ! Mint
        case (6)
            color = '#F38181'  ! Pink
        case (7)
            color = '#AA96DA'  ! Purple
        case default
            color = '#666666'  ! Gray
        end select
        
        color_str = color
    end function get_color

end program nrings_svg
